name: Drugs
main: com.starfire1337.drugs.Drugs
description: An ultimate configurable drugs plugin
version: ${version}
author: Starfire1337
commands:
  drugs:
    description: The administrator command for the plugin Drugs
    permission: drugs.admin
    usage: /<command>
    aliases: [drug]